version: '3'
services:
  phpipam-web:
    image: phpipam/phpipam-www:latest
    container_name: phpipam-web
    hostname: phpipam-web
    restart: unless-stopped
    environment:
      - TZ=American/Chicago
      - IPAM_DATABASE_HOST=phpipam-mariadb
      - IPAM_DATABASE_WEBHOST=%
    depends_on:
      - phpipam-mariadb
    labels:
      # Traefik Labels
      - "traefik.enable=true"
      # HTTPS Labels
      - "traefik.http.routers.phpipam.rule=Host(`localhost`)" # Domain Name
      - "traefik.http.routers.phpipam.entrypoints=web-secure"
      - "traefik.http.routers.phpipam.middlewares=default-headers@file"
      - "traefik.http.routers.phpipam.service=phpipam"
      - "traefik.http.routers.phpipam.tls=true"
      - "traefik.http.services.phpipam.loadbalancer.server.port=80" # Proxied Port
  phpipam-cron:
    image: phpipam/phpipam-cron:latest
    container_name: phpipam-cron
    hostname: phpipam-cron
    restart: unless-stopped
    environment:
      - TZ=American/Chicago
      - IPAM_DATABASE_HOST=phpipam-mariadb
      - SCAN_INTERVAL=1h
    depends_on:
      - phpipam-mariadb
  phpipam-mariadb:
    image: mariadb:latest
    container_name: phpipam-mariadb
    hostname: phpipam-mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=example
    volumes:
      - ../Data/mysql:/var/lib/mysql
